# Thank you for using SaveIt on your Server.
# If you don't understand something please visit: https://www.dropbox.com/s/zj1ue8ez3udmn9c/Saving%20It%20Documentation.pdf
EnableDelay: true
DelayInMinutes: 10
# World Name Should be Exactly the same of the directory.
# You can now use SaveAllWorlds instead of the list.
Worlds:
- world
- world_nether
- world_the_end
EnableSaveMSG: true
SaveMSG: '&aStarting world save...'
SaveMSG2: '&aWorld save completed!'
SavePlayersEverywhere: false
CheckForUpdates: true
DisableDefaultWorldSave: true
ExtraOptions:
  SaveOnLogin: false
  SaveOnLoginCount: 50
  SaveOnQuit: false
  SaveOnQuitCount: 50
  SaveOnBlockBreak: false
  SaveOnBlockPlace: false
  SaveOnBlockBreakcount: 500
  SaveOnBlockPlacecount: 500
  SaveOnDisable: true
  EnableSelfInventorySave: false
  EnableDebugMSGs: false
# This Should be true, but It's up to your decision. Read The PDF About this.
EnablePowerSave: false
SaveAllWorlds: false
BroadCastWorldErrorIg: false