name: SaveIt
main: me.dretax.SaveIt.Main
version: ${version}
authors: [DreTaX]
commands:
  saveit:
    description: Main Command Lister.
permissions:
    saveit.save:
        description: For the /saveit save command
        default: op
    saveit.reload:
        description: For the /saveit reload command
        default: op
    saveit.selfsave:
        description: For the /saveit selfsave command
        default: op
    saveit.manage:
        description: For the /saveit [add/remove/list] command
        default: op
    saveit.backup:
        description: For the /saveit backup command
        default: op